# Generated by Django 3.1 on 2020-08-14 09:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(default=0)),
                ('file_name', models.CharField(max_length=64)),
                ('file_foundTime', models.DateTimeField(auto_now_add=True)),
                ('file_lastBrowseTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_lastModifiedTime', models.DateTimeField(auto_now=True)),
                ('file_doc', models.FileField(upload_to='word/')),
                ('file_size', models.IntegerField(default=0)),
                ('file_text', models.TextField(default='')),
                ('file_is_delete', models.SmallIntegerField(default=0)),
                ('file_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('file_id',)},
            },
        ),
        migrations.CreateModel(
            name='FileReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=512)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.fileinformation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('file_id',)},
            },
        ),
    ]
