# Generated by Django 3.1 on 2020-08-13 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInfomation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=64)),
                ('file_foundTime', models.DateTimeField(auto_now_add=True)),
                ('file_lastModifiedTime', models.DateTimeField(auto_now=True)),
                ('file_doc', models.FileField(upload_to='word/')),
                ('file_size', models.IntegerField(default=0)),
                ('file_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
        ),
    ]
