# Generated by Django 3.1 on 2020-08-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0002_fileinformation_filereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinformation',
            name='file_is_free',
            field=models.SmallIntegerField(default=1),
        ),
    ]
