# Generated by Django 3.1 on 2020-08-13 18:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0002_fileinfomation'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfomation',
            name='file_lastBrowseTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
