# Generated by Django 3.1 on 2020-08-14 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0003_fileinformation_file_is_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinformation',
            name='file_doc',
        ),
        migrations.RemoveField(
            model_name='fileinformation',
            name='file_size',
        ),
    ]
