# Generated by Django 3.1 on 2020-08-14 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0004_auto_20200814_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileinformation',
            name='file_lastBrowseTime',
        ),
        migrations.CreateModel(
            name='RecentBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browse_time', models.DateTimeField(auto_now=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.fileinformation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('user_id', 'file_id')},
            },
        ),
    ]
