# Generated by Django 3.1 on 2020-08-14 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0005_auto_20200814_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.IntegerField(default=1597410077)),
                ('team_name', models.CharField(max_length=16)),
                ('team_description', models.CharField(max_length=256)),
                ('team_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('team_id',)},
            },
        ),
    ]
