# Generated by Django 3.1 on 2020-08-15 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0007_auto_20200815_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='team_id',
            field=models.IntegerField(default=1597454906),
        ),
        migrations.CreateModel(
            name='SpecificAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_file', models.SmallIntegerField()),
                ('write_file', models.SmallIntegerField()),
                ('share_file', models.SmallIntegerField()),
                ('review_file', models.SmallIntegerField()),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.fileinformation')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('user_info', 'file_info')},
            },
        ),
    ]
