# Generated by Django 3.1 on 2020-08-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0008_auto_20200815_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaminfo',
            name='team_id',
            field=models.IntegerField(default=1597476422),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_id', models.IntegerField(default=1597476422)),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.fileinformation')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('user_info', 'file_info', 'favorite_id')},
            },
        ),
    ]
