# Generated by Django 3.1 on 2020-08-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0009_auto_20200815_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorite_id',
            field=models.IntegerField(default=1597476691),
        ),
        migrations.AlterField(
            model_name='teaminfo',
            name='team_id',
            field=models.IntegerField(default=0),
        ),
    ]
