# Generated by Django 3.1 on 2020-08-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0010_auto_20200815_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='favorite_id',
            field=models.IntegerField(default=0),
        ),
    ]
