# Generated by Django 3.1 on 2020-08-15 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0011_auto_20200815_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.teaminfo')),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('team_info', 'user_info')},
            },
        ),
    ]
