# Generated by Django 3.1 on 2020-08-15 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0012_teamuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.fileinformation')),
                ('team_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.teaminfo')),
            ],
            options={
                'unique_together': {('file_info', 'team_info')},
            },
        ),
    ]
