# Generated by Django 3.1 on 2020-08-16 06:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0013_teamfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='filereview',
            name='review_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DocTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_id', models.IntegerField(default=0)),
                ('template_text', models.TextField(default='')),
                ('template_name', models.CharField(max_length=32)),
            ],
            options={
                'unique_together': {('template_id',)},
            },
        ),
    ]
