# Generated by Django 3.1 on 2020-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0015_notificationsinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsinfo',
            name='is_new',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='notificationsinfo',
            name='notification_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='notificationsinfo',
            name='receive_info',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='notificationsinfo',
            name='post_info',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsinfo',
            unique_together={('post_info', 'receive_info')},
        ),
    ]
