# Generated by Django 3.1 on 2020-08-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0016_auto_20200816_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsinfo',
            name='is_invitation',
            field=models.SmallIntegerField(default=0),
        ),
    ]
