# Generated by Django 3.1 on 2020-08-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0017_notificationsinfo_is_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsinfo',
            name='noti_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='notificationsinfo',
            unique_together={('noti_id', 'post_info', 'receive_info')},
        ),
    ]
