# Generated by Django 3.1 on 2020-08-16 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0018_auto_20200816_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsinfo',
            name='post_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
