# Generated by Django 3.1 on 2020-08-18 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0019_notificationsinfo_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=512)),
                ('review_time', models.DateTimeField(auto_now_add=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.fileinformation')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.userinfo')),
            ],
            options={
                'unique_together': {('file_id', 'user_id')},
            },
        ),
    ]
