# Generated by Django 3.0.8 on 2020-08-10 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diamond_doc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInfo',
            fields=[
                ('admin_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_account', models.CharField(max_length=16)),
                ('admin_password', models.CharField(max_length=16)),
                ('admin_nickname', models.CharField(max_length=16)),
                ('admin_icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('favorite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_num', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.UserInfo')),
            ],
            options={
                'unique_together': {('user_id',)},
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=16)),
                ('team_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('file_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=64)),
                ('file_foundTime', models.DateTimeField(auto_now_add=True)),
                ('file_lastModifiedTime', models.DateTimeField(auto_now=True)),
                ('file_founder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.UserInfo')),
                ('file_teamBelong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.TeamInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TeamUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.TeamInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.UserInfo')),
            ],
            options={
                'unique_together': {('team_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='SpecificAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_file', models.SmallIntegerField()),
                ('write_file', models.SmallIntegerField()),
                ('share_file', models.SmallIntegerField()),
                ('review_file', models.SmallIntegerField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.FileInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.UserInfo')),
            ],
            options={
                'unique_together': {('user_id', 'file_id')},
            },
        ),
        migrations.CreateModel(
            name='RecycleBin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_dir', models.URLField()),
                ('deleted_time', models.DateTimeField(auto_now_add=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.FileInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.UserInfo')),
            ],
            options={
                'unique_together': {('file_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='RecentBrowse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browse_time', models.DateTimeField(auto_now=True)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.FileInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.UserInfo')),
            ],
            options={
                'unique_together': {('user_id', 'file_id')},
            },
        ),
        migrations.CreateModel(
            name='GeneralAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_file', models.SmallIntegerField()),
                ('write_file', models.SmallIntegerField()),
                ('share_file', models.SmallIntegerField()),
                ('review_file', models.SmallIntegerField()),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.FileInfo')),
            ],
            options={
                'unique_together': {('file_id',)},
            },
        ),
        migrations.CreateModel(
            name='FileReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.CharField(max_length=512)),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.FileInfo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.UserInfo')),
            ],
            options={
                'unique_together': {('file_id',)},
            },
        ),
        migrations.CreateModel(
            name='FavoritesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.Favorites')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diamond_doc.FileInfo')),
            ],
            options={
                'unique_together': {('favorite_id', 'file_id')},
            },
        ),
    ]
